# Generated by Django 3.2.3 on 2021-05-19 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Smartphone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title product')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField(null=True, verbose_name='description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='price')),
                ('make', models.CharField(max_length=255, verbose_name='make')),
                ('diagonal', models.CharField(max_length=255, verbose_name='diagonal')),
                ('display_type', models.CharField(max_length=255, verbose_name='display type')),
                ('ram', models.CharField(max_length=255, verbose_name='ram')),
                ('sd', models.BooleanField(default=True, verbose_name='sd')),
                ('main_cam', models.CharField(max_length=255, verbose_name='main cam')),
                ('frontal_cam', models.CharField(max_length=255, verbose_name='frontal cam')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title product')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField(null=True, verbose_name='description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='price')),
                ('make', models.CharField(max_length=255, verbose_name='make')),
                ('diagonal', models.CharField(max_length=255, verbose_name='diagonal')),
                ('display_type', models.CharField(max_length=255, verbose_name='display_type')),
                ('processor_freq', models.CharField(max_length=255, verbose_name='processor_freq')),
                ('ram', models.CharField(max_length=255, verbose_name='ram')),
                ('graphics', models.CharField(max_length=255, verbose_name='graphics')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
